version: "3.9"
services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && gunicorn TrueGarageApp.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./config/nginx.config:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
  db:
    image: postgres:14.5
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  client_bot:
    build: ./client_bot
    command: python3 main.py
    volumes:
      - ./client_bot:/client_bot
    depends_on:
      - web
volumes:
  static_volume:
  db_data: