# Generated by Django 5.0.3 on 2024-03-25 15:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ad', models.DateTimeField(default=datetime.datetime(2024, 3, 25, 15, 16, 41, 678267))),
                ('user_name', models.CharField(max_length=100)),
                ('hash_password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 25, 15, 16, 41, 679123))),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('at_work', 'В работе'), ('waiting_to_start', 'Ожидает начала'), ('waiting_to_details', 'Ожидает детали'), ('requires_clarification', 'Требует уточнения деталий')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 25, 15, 16, 41, 678917))),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Engineers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('works', 'Работает'), ('on_holiday', 'В отпуске'), ('medical_leave', 'На больничном')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.users')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.users'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 25, 15, 16, 41, 679286))),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.clients')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.engineers')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.motorcycles')),
                ('works', models.ManyToManyField(to='admin_app.works')),
            ],
        ),
    ]
