# Generated by Django 5.0.3 on 2024-04-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
