# Generated by Django 5.0.3 on 2024-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_client_description_alter_engineer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='status',
            field=models.CharField(choices=[('work', 'Работает'), ('not_work', 'Не работает')], default='work', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_queue', 'В очереди'), ('in_progress', 'В работе'), ('ready', 'Готов')], default='in_queue', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_queue', 'В очереди'), ('in_progress', 'В работе'), ('awaiting_approval', 'На согласовании'), ('waiting_for_delivery', 'Ожидает поставку'), ('ready', 'Готов')], default='in_queue', max_length=100),
        ),
    ]
