# Generated by Django 5.0.3 on 2024-03-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_motorcycles_created_at_alter_orders_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Engineers',
            new_name='Engineer',
        ),
        migrations.RenameModel(
            old_name='Motorcycles',
            new_name='Motorcycle',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
