# Generated by Django 5.0.3 on 2024-04-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_engineer_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='count',
            field=models.FloatField(default=1),
        ),
    ]
