# Generated by Django 5.0.3 on 2024-03-28 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_client_email_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='work',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='work',
            name='status',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='mfg_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='state_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_queue', 'В очереди'), ('in_progress', 'В работе'), ('ready', 'Готов')], default='in_queue', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engineer',
            name='status',
            field=models.CharField(choices=[('work', 'Работает'), ('not_work', 'Не работает')], max_length=100),
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.supply')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('in_queue', 'В очереди'), ('in_progress', 'В работе'), ('awaiting_approval', 'На согласовании'), ('waiting_for_delivery', 'Ожидает поставку'), ('ready', 'Готов')], max_length=100)),
                ('supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.supplies')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.work')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.user'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.user'),
        ),
    ]
