# Generated by Django 5.0.4 on 2024-04-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='admin_app.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Engineer', to='admin_app.engineer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Motorcycle', to='admin_app.motorcycle'),
        ),
    ]
