# Generated by Django 5.0.3 on 2024-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_supply_user_remove_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='works',
        ),
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ManyToManyField(to='admin_app.task'),
        ),
    ]
