# Generated by Django 5.0.4 on 2024-04-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.FloatField(default=0, verbose_name='Предоплата (Руб.):'),
        ),
        migrations.AddField(
            model_name='order',
            name='supply_discount',
            field=models.FloatField(default=0, verbose_name='Скидка на запчасти (%):'),
        ),
        migrations.AddField(
            model_name='order',
            name='task_discount',
            field=models.FloatField(default=0, verbose_name='Скидка на работы (%):'),
        ),
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
