# Generated by Django 5.0.4 on 2024-04-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_remove_order_discount_order_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='engineer',
        ),
        migrations.AddField(
            model_name='order',
            name='engineers',
            field=models.ManyToManyField(to='admin_app.engineer'),
        ),
    ]
