# Generated by Django 5.0.3 on 2024-03-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
    ]
