# Generated by Django 5.0.3 on 2024-03-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_remove_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
