# Generated by Django 5.0.3 on 2024-03-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='task',
            field=models.ManyToManyField(limit_choices_to={'child__isnull': True}, to='admin_app.task'),
        ),
    ]
