# Generated by Django 5.0.4 on 2024-04-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_order_engineers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='engineers',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='EngineerList', to='admin_app.engineer'),
        ),
    ]
