# Generated by Django 5.0.3 on 2024-03-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_order_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_app.order'),
            preserve_default=False,
        ),
    ]
