# Generated by Django 5.0.4 on 2024-04-15 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_alter_order_engineers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='engineers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EngineerList', to='admin_app.engineer'),
        ),
    ]
