# Generated by Django 5.0.3 on 2024-04-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_remove_order_task_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ManyToManyField(to='admin_app.task'),
        ),
    ]
