# Generated by Django 5.0.4 on 2024-04-15 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_alter_order_engineers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='engineer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Engineer', to='admin_app.engineer'),
        ),
    ]
