# Generated by Django 5.0.3 on 2024-04-01 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_remove_task_order_order_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.order')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.task')),
            ],
            options={
                'unique_together': {('order', 'task')},
            },
        ),
    ]
