# Generated by Django 5.0.3 on 2024-04-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_ordertasklink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_app.order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderTaskLink',
        ),
    ]
