# Generated by Django 5.0.3 on 2024-04-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_remove_order_task_task_order_delete_ordertasklink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='supplies',
        ),
        migrations.AddField(
            model_name='supplies',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_app.task'),
            preserve_default=False,
        ),
    ]
