# Generated by Django 5.0.4 on 2024-04-30 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_alter_order_engineers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_app.order'),
        ),
    ]
