# Generated by Django 5.0.4 on 2024-04-30 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplies', to='admin_app.order'),
        ),
    ]
